In [1]:
import numpy as np

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Task: From a, select elements that are divisible by 2

print(a[a % 2 == 0])

[ 2  4  6  8 10 12]


In [ ]:
# Task: From a, select elements that are greater than 2 and less than or equal to 10

print(a[(a > 2) & (a <= 10)])

[ 3  4  5  6  7  8  9 10]


In [2]:
# Task: for 2D array with and without axis

the_array = np.array([[3, 2, 5], [2, 1, 7]])
the_array.shape

(2, 3)

In [3]:
unique_values, unique_occurrences = np.unique(the_array, return_counts=True)

print(f"Unique Values: {unique_values}")
print(f"Occurence count: {unique_occurrences}")

Unique Values: [1 2 3 5 7]
Occurence count: [1 2 1 1 1]


In [4]:
unique_values, unique_occurrences = np.unique(the_array, return_counts=True, axis=0)

print(f"Unique Values: {unique_values}")
print(f"Occurence count: {unique_occurrences}")

Unique Values: [[2 1 7]
 [3 2 5]]
Occurence count: [1 1]


In [5]:
unique_values, unique_occurrences = np.unique(the_array, return_counts=True, axis=1)

print(f"Unique Values: {unique_values}")
print(f"Occurence count: {unique_occurrences}")

Unique Values: [[2 3 5]
 [1 2 7]]
Occurence count: [1 1 1]


In [11]:
# working with numpy array

array_2d = np.array([[1, 10, 3, 4], [8, 7, 6, 5], [9, 2, 11, 12]])

array_2d[:, 1] = np.flip(array_2d[:, 1])
print(array_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
