# Word Embeddings in NLP

Word Embeddings is converting words into vectors.

![tree of embeddings](./embeddings.png)

### 1. One Hot Encoding

Each word is represented as a binary vector with the length of the entire vocabulary. The vector has a "1" in the position corresponding to word's index and "0" elsewhere.

Pros:
- Simple, interpretable.
Cons:
- High dimensionality, doesn't capture semantic relationships.

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Sample data
corpus = ['dog', 'cat', 'dog', 'fish']

# Reshape data to fit the model
corpus = np.array(corpus).reshape(-1, 1)

# One-hot encode the data
onehot_encoder = OneHotEncoder()
onehot_encoded = onehot_encoder.fit_transform(corpus)

print(onehot_encoded)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 3)>
  Coords	Values
  (0, 1)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 2)	1.0


### 2. Bag of Words (BoW)

It's a simple technique in NLP for representing text documents as numerical vectors. The idea is to treat each document as a bag, or a collection, of words, then count frequency of each word in the document. It doesn't consider the order of words but provides straightforward way to convert text into vectors.

Pros:
- Simple, capture word importance based on frequency
Cons:
- Ignore word order and context

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

# Sample data
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the corpus
X = vectorizer.fit_transform(corpus)

print(X.toarray())
print(vectorizer.get_feature_names_out())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


### 3. TF-IDF (Term Frequency-Inverse Document Frequency)

It's an improvement over BoW. The idea is to calculate importance of a word in a document by considering two factors:

1. Term Frequency (TF): It measures how frequently a term appears in `a document`. Higher frequency of a term equates to more importance.

1. Inverse Document Frequency (IDF): It's a measure of how important a term is across `all document in the corpus`. It's based on the intuition that terms that appear in many documents are less informative than terms that appears in fewer documents.

TF-IDF = TF * IDF

It's used to rank the importance of words in a document.

Pros:
- Considers both term frequency and rarity.
Cons:
- Still doesn't capture the semantic relationship.

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Sample data
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

# Initialize the TfidfVectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the corpus
X = vectorizer.fit_transform(corpus)

print(X.toarray())
print(vectorizer.get_feature_names_out())

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]
['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


### 4. Word2Vec

It's a neural network based model that generates dense vector representations of words. The idea is to train a neural network to predict the context words given a target word, and then use the resulting vector representations to capture the semantic meaning of words. It captures semantic relationships between words using two main approaches: CBOW (Continuous Bag of Words) and Skip-gram.

- Continuous Bag-of-Words(CBOW): it predicts the target word given its surrounding context words.
- Skip-Gram: it predicts surrounding context words given a target word.

Pros:
- Captures semantic relationships between words, lower dimensionality than classical methods
Cons:
- Requires training on a large corpus, doesn't handle out-of-vocabulary words (OOV) well.

In [8]:
from gensim.models import Word2Vec

# Sample data
sentences = [
    ['this', 'is', 'the', 'first', 'document'],
    ['this', 'document', 'is', 'the', 'second', 'document'],
    ['and', 'this', 'is', 'the', 'third', 'one'],
    ['is', 'this', 'the', 'first', 'document']
]

# Initialize the Word2Vec model
model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)

# Train the model
model.train(sentences, total_examples=len(sentences), epochs=10)

# Get vector for a word
print(model.wv['document'])

[-5.3622725e-04  2.3643136e-04  5.1033497e-03  9.0092728e-03
 -9.3029495e-03 -7.1168090e-03  6.4588725e-03  8.9729885e-03
 -5.0154282e-03 -3.7633716e-03  7.3805046e-03 -1.5334714e-03
 -4.5366134e-03  6.5540518e-03 -4.8601604e-03 -1.8160177e-03
  2.8765798e-03  9.9187379e-04 -8.2852151e-03 -9.4488179e-03
  7.3117660e-03  5.0702621e-03  6.7576934e-03  7.6286553e-04
  6.3508903e-03 -3.4053659e-03 -9.4640139e-04  5.7685734e-03
 -7.5216377e-03 -3.9361035e-03 -7.5115822e-03 -9.3004224e-04
  9.5381187e-03 -7.3191668e-03 -2.3337686e-03 -1.9377411e-03
  8.0774371e-03 -5.9308959e-03  4.5162440e-05 -4.7537340e-03
 -9.6035507e-03  5.0072931e-03 -8.7595852e-03 -4.3918253e-03
 -3.5099984e-05 -2.9618145e-04 -7.6612402e-03  9.6147433e-03
  4.9820580e-03  9.2331432e-03 -8.1579173e-03  4.4957981e-03
 -4.1370760e-03  8.2453608e-04  8.4986202e-03 -4.4621765e-03
  4.5175003e-03 -6.7869602e-03 -3.5484887e-03  9.3985079e-03
 -1.5776526e-03  3.2137157e-04 -4.1406299e-03 -7.6826881e-03
 -1.5080082e-03  2.46979

### 5. GloVe(Global Vectors for Word Representation)

It's an unsupervised learning algorithm for obtaining vector representation of words. It aims to capture both global word co-occurrence statistics and local context window-based information (like Word2Vec) to create high quality word vectors. The core idea is that the ratios of word-word co-occurence probabilities encode meaningful semantic relationships. For example, consider the words “ice” and “steam” and their co-occurrence probabilities with other words like “solid” and “gas.” The ratio P(solid | ice) / P(solid | steam) would be high, indicating a stronger association between "ice" and "solid" compared to "steam" and "solid." GloVe leverages these ratios to learn word vectors.

Pros: 
- Captures both global and local context
- faster training than Word2Vec
Cons:
- similar to Word2Vec in terms of OOV words

In [9]:
import gensim.downloader as api

# Download pre-trained GloVe model (choose the size you need - 50, 100, 200, or 300 dimensions)
glove_vectors = api.load("glove-wiki-gigaword-100")  # Example: 100-dimensional GloVe

# Get word vectors (embeddings)
word1 = "king"
word2 = "queen"
vector1 = glove_vectors[word1]
vector2 = glove_vectors[word2]

# Compute cosine similarity between the two word vectors
similarity = glove_vectors.similarity(word1, word2)

print(f"Word vectors for '{word1}': {vector1}")
print(f"Word vectors for '{word2}': {vector2}")
print(f"Cosine similarity between '{word1}' and '{word2}': {similarity}")

[==================================================] 100.0% 128.1/128.1MB downloaded
Word vectors for 'king': [-0.32307  -0.87616   0.21977   0.25268   0.22976   0.7388   -0.37954
 -0.35307  -0.84369  -1.1113   -0.30266   0.33178  -0.25113   0.30448
 -0.077491 -0.89815   0.092496 -1.1407   -0.58324   0.66869  -0.23122
 -0.95855   0.28262  -0.078848  0.75315   0.26584   0.3422   -0.33949
  0.95608   0.065641  0.45747   0.39835   0.57965   0.39267  -0.21851
  0.58795  -0.55999   0.63368  -0.043983 -0.68731  -0.37841   0.38026
  0.61641  -0.88269  -0.12346  -0.37928  -0.38318   0.23868   0.6685
 -0.43321  -0.11065   0.081723  1.1569    0.78958  -0.21223  -2.3211
 -0.67806   0.44561   0.65707   0.1045    0.46217   0.19912   0.25802
  0.057194  0.53443  -0.43133  -0.34311   0.59789  -0.58417   0.068995
  0.23944  -0.85181   0.30379  -0.34177  -0.25746  -0.031101 -0.16285
  0.45169  -0.91627   0.64521   0.73281  -0.22752   0.30226   0.044801
 -0.83741   0.55006  -0.52506  -1.7357    0.4751  

### 6. FastText

Unlike Word2Vec, Glove, FastText considers words as a bag of character n-grams (subwords). An n-gram is a contiguous sequence of n characters.

By utilizing subword information, FastText can generate meaningful representations for rare words or words not seen during training. It's useful in morphologically rich languages (e.g. agglutinative languages) and where the vocabulary is constantly evolving.

The two key techniques employed by FastText to achieve high speed are:
- Hierarchical Softmax:
    - It's used to represent output labels, significantly reducing computational complexity of softmax function during training and prediction.
- Negative Sampling:
    - Only a small subset of output labels (negative samples) are updated during training, making updates much faster.

Pros:
- handles OOV words
- captures morphological information
Cons:
- Higher dimensionality than Word2Vec

In [10]:
from gensim.models import FastText

# Sample data
sentences = [
    ['this', 'is', 'the', 'first', 'document'],
    ['this', 'document', 'is', 'the', 'second', 'document'],
    ['and', 'this', 'is', 'the', 'third', 'one'],
    ['is', 'this', 'the', 'first', 'document']
]

# Initialize the FastText model
model = FastText(sentences, vector_size=100, window=5, min_count=1, workers=4)

# Train the model
model.train(sentences, total_examples=len(sentences), epochs=10)

# Get vector for a word
print(model.wv['document'])

[ 7.28658633e-04  4.16975323e-04 -9.04823013e-04  1.81001960e-03
 -1.67903654e-05 -3.09501472e-03 -8.94924597e-05  1.52686599e-03
  8.70525721e-04 -9.01299238e-04  1.43874600e-03  5.59412183e-05
  4.59743809e-04  3.46187595e-03  8.36980762e-04 -1.69622083e-03
  3.13669851e-04 -7.36940594e-04  6.58333665e-05 -5.58551459e-04
  9.99022392e-04  7.64884113e-04  2.00318667e-04  8.93982826e-04
 -3.39016761e-03  9.25415254e-04  1.11034795e-04 -8.58929066e-04
  1.25828237e-05  1.05972786e-05 -8.64572416e-04 -3.38818500e-04
 -1.39185390e-03  2.87857492e-05  1.37834053e-03  2.59727211e-04
  1.30050757e-03 -4.25247534e-04 -7.64057448e-04  1.27068837e-03
 -1.51411525e-03 -6.99590892e-05 -4.52115142e-04  7.29623483e-04
  4.04204417e-04 -1.35204216e-04 -5.19728346e-04  2.75263912e-03
 -3.28213559e-04 -3.32455500e-04 -1.98965732e-04  5.10342361e-04
 -9.89962136e-04  1.53860752e-03  8.56888772e-04  1.58262334e-03
  4.72602871e-04  1.90332241e-03 -1.62470201e-03  5.29104436e-04
  6.73180853e-04 -6.79468

### 7. ELMo (Embeddings from Language Models)

It's a deep contextualized word representation that models both complex characteristics of word use (e.g. syntax and semantics) and how these uses vary across linguistic contexts (e.g. to model polysemy). ELMo generates context-sensitive embeddings using deep bi-directional LSTM and provides different embeddings for words based on their context.

Key features of ELMo:
- Contextualized Representations:
    - ELMo embeddings vary on depending on context of words.
    - it's different from traditional embeddings like Word2Vec or GloVe, which provide single representation for each word regardless of context.
- Deep Representations:
    - ELMo uses deep bidirectional LSTM networks to generate embeddings, capturing complex syntactic and semantic information.
- Layer-wise Representations:
    - ELMo combines representations from all layers of biLSTM, that allows it to capture different types of information at different layers.

Pros:
- Contextualized embeddings
- Bi-directional context
Cons:
- Complexity and size
- Fixed content window

In [ ]:
import tensorflow as tf
import tensorflow_hub as hub

# Load pre-trained ELMo model from TensorFlow Hub
elmo = hub.load("https://tfhub.dev/google/elmo/3")

# Sample data
sentences = ["This is the first document.", "This document is the second document."]

def elmo_vectors(sentences):
    embeddings = elmo.signatures['default'](tf.constant(sentences))['elmo']
    return embeddings

# Get ELMo embeddings
elmo_embeddings = elmo_vectors(sentences)
print(elmo_embeddings)

### 8. BERT (Bidirectional Encoder Representations from Transformers)

BERT is transformer based model that generates context-aware embeddings by considering the entire sentence bidirectionally (i.e. both left-to-right and right-to-left). Unlike traditional word embeddings like Word2Vec or GloVe, which generate single representation for each word, BERT produces different embeddings for each word based on its context. Key features of BERT are:

- Encoder:
    - main component of BERT architecture, consisting of multiple transformer encoder layers.
    - each encoder layer has multi-head self attention mechanism that allows the model to attend to different positions in the input sequence when encoding a specific token.
    - self-attention mechanism is bidirectional, meaning that encoding of a token can attend to both left and right context of the sequence.
    - each encoder layer also has a position wise feed-forward network, which applies non-linear transformations to the output of the self-attention mechanism.

- Pre-trained on Large Corpus:
    - BERT is based on large corpus of unlabeled text using two main objectives:
        - Masked Language Modeling (MLM):
            - in this task, some tokens int input sequence are randomly masked (replaced with [MASK] token) and model is trained to predict the masked tokesn based on the context.
        - Next Sentence Prediction (NSP):
            The model is trained to predict whether two input sentences are consecutive in the original text or not.

- Fine-tuning:
    - Parameters of pre-trained BERT model are fine-tuned using labeled data for the target task, while output layer is trained from scratch.
    - This transfer learning approach allows BERT to leverage its pre-trained knowledge and adapt to new tasks with relatively small amounts of labeled data.


Pros:
- pre-training & fine-tuning
- contextualized embeddings
- bidirectional context
Cons:
- complexity and size
- complexity
- inference time

In [11]:
from transformers import BertTokenizer, BertModel
import torch

# Load pre-trained BERT model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Sample data
sentence = "This is the first document."

# Tokenize input
inputs = tokenizer(sentence, return_tensors='pt')

# Get embeddings
with torch.no_grad():
    outputs = model(**inputs)
    embeddings = outputs.last_hidden_state

print(embeddings)

/home/sudip/Desktop/Accelerate/NLP_foundation/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.


ModuleNotFoundError: No module named 'torch'