### Common terms used while repersenting text in NLP:

- Corpus (C): All the text data or records of dataset together are k.a. corpus.
- Vocabulary (V): All unique words present in the corpus.
- Document (D): One single text record of the dataset is a Document.
- Word (W): The words present in the vocabulary.

Types of text representation in NLP:
- Discrete text representation
- Distribued text representation

Some of the discrete text representation in NLP are:
- One Hot Encoding
- Bag of Words
- Count Vectorizer
- TF-IDF
- Ngrams

### 1. One Hot Encoding

In [1]:
from sklearn.preprocessing import OneHotEncoder
import itertools

document = ["The","boy","sat","on","the","floor"]
#we have to convert these tokens to a dictionary with the key as word and value as position

tokens = [doc.split(" ") for doc in document]
token_chain = itertools.chain.from_iterable(tokens)
word_to_id = {token: idx for idx, token in enumerate(set(token_chain))}
#word_to_id is our required dictionary
#Get the corresponding values for each word
token_ids = [[word_to_id[token] for token in toke] for toke in tokens]

vec = OneHotEncoder(categories="auto")
V = vec.fit_transform(token_ids)
print(V.toarray())


[[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]]


### 2. Count Vectorizer

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
document = ["NLP has changed the world. I love NLP. NLP is cool"]
vectorizer = CountVectorizer()
# tokenize and build vocabulary
vectorizer.fit(document)
print(vectorizer.vocabulary_)
# encode document
vector = vectorizer.transform(document)
# summarize encoded vector
print(vector.toarray())

{'nlp': 5, 'has': 2, 'changed': 0, 'the': 6, 'world': 7, 'love': 4, 'is': 3, 'cool': 1}
[[1 1 1 1 1 3 1 1]]


### 3. TF-IDF

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
text = ['NLP has changed the world', 'I love NLP', 'NLP is cool', 'NLP is future']
tf = TfidfVectorizer()
txt_fit = tf.fit(text)
txt_transform = txt_fit.transform(text)
idf = tf.idf_
print(dict(zip(txt_fit.get_feature_names_out(), idf)))


{'changed': np.float64(1.916290731874155), 'cool': np.float64(1.916290731874155), 'future': np.float64(1.916290731874155), 'has': np.float64(1.916290731874155), 'is': np.float64(1.5108256237659907), 'love': np.float64(1.916290731874155), 'nlp': np.float64(1.0), 'the': np.float64(1.916290731874155), 'world': np.float64(1.916290731874155)}


### 4. N-grams

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

text = ['NLP has changed the world', 'I love NLP', 'NLP is cool', 'NLP is future']

# token_pattern allows 1-character words like "I"
cv = CountVectorizer(ngram_range=(2, 2), token_pattern=r"(?u)\b\w+\b")

bow = cv.fit_transform(text)

print("Vocabulary Groups (Bigrams):")
print(cv.vocabulary_)
print("\nVector representation of the first sentence:")
print(bow[0].toarray())

Vocabulary Groups (Bigrams):
{'nlp has': 6, 'has changed': 1, 'changed the': 0, 'the world': 8, 'i love': 2, 'love nlp': 5, 'nlp is': 7, 'is cool': 3, 'is future': 4}

Vector representation of the first sentence:
[[1 1 0 0 0 0 1 0 1]]
